## 00. PyTorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [2]:
import torch
import pandas as pd
import numpy as np
import plotly.express as px
print(torch.__version__)

2.0.1+cu118


In [3]:
!nvidia-smi

Wed Aug  9 20:04:47 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.67                 Driver Version: 536.67       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090      WDDM  | 00000000:01:00.0  On |                  Off |
|  0%   37C    P8              20W / 450W |    961MiB / 24564MiB |      8%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Introduction to Tensors

### Creating tensors

In [4]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

In [16]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are imrtant becau the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers -> ...`

In [20]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(1, 10, 10)
random_tensor

tensor([[[0.4570, 0.4166, 0.2337, 0.3485, 0.4416, 0.6975, 0.5694, 0.5115,
          0.6803, 0.3534],
         [0.0489, 0.2912, 0.3648, 0.3862, 0.2141, 0.3760, 0.9374, 0.2230,
          0.3231, 0.3142],
         [0.0090, 0.8559, 0.8331, 0.2194, 0.4221, 0.6825, 0.8643, 0.0085,
          0.4953, 0.9831],
         [0.0153, 0.2337, 0.5214, 0.8048, 0.8797, 0.0251, 0.8141, 0.8197,
          0.6943, 0.8928],
         [0.5367, 0.9495, 0.1563, 0.8114, 0.4002, 0.4694, 0.0972, 0.3191,
          0.5912, 0.4135],
         [0.3884, 0.5858, 0.5750, 0.4303, 0.7716, 0.5127, 0.8690, 0.4044,
          0.7273, 0.6532],
         [0.2312, 0.7379, 0.1766, 0.8066, 0.8194, 0.3791, 0.4541, 0.1268,
          0.3339, 0.1928],
         [0.0992, 0.2843, 0.2695, 0.4887, 0.7684, 0.5928, 0.2394, 0.7571,
          0.6592, 0.0030],
         [0.2058, 0.2531, 0.6980, 0.2081, 0.2590, 0.5266, 0.2336, 0.3856,
          0.9229, 0.3217],
         [0.3529, 0.8322, 0.4443, 0.1486, 0.7298, 0.1222, 0.4153, 0.6160,
          0.7522,

In [22]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [23]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [27]:
# Use torch.range()
torch.range(0, 10)

C:\Users\Krisztian\AppData\Local\Temp\ipykernel_5900\1840815090.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
# Use arange instead of range
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# With step
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [30]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not the right device

In [33]:
# Default dtype is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [34]:
float_32_tensor.dtype

torch.float32

In [35]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [43]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=torch.float16, # What datatype is the tensor (e.g. float32 or float16)
                               device=None,         # What device is your tensor on
                               requires_grad=False) # Whether or not to track gradients with this tensor operations
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [44]:
float_16_tensor.dtype

torch.float16

In [45]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [46]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [47]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [48]:
# Create a tensor
some_tensor = torch.rand(size=(3,4))
some_tensor

tensor([[0.7043, 0.0844, 0.8238, 0.5053],
        [0.9978, 0.3536, 0.1753, 0.7555],
        [0.1972, 0.6036, 0.7900, 0.8568]])

In [49]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.7043, 0.0844, 0.8238, 0.5053],
        [0.9978, 0.3536, 0.1753, 0.7555],
        [0.1972, 0.6036, 0.7900, 0.8568]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [50]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [51]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [52]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [53]:
# Try out PyTorch in-build functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways of performing multiplication in neural networkds and deep learning:

1. Element-wise multiplication
2. Matrix multiplication

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [55]:
# Element wise multiplication

print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [56]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [62]:
%%timeit
# Matrix multiplication by hand
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

14.5 µs ± 116 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [63]:
%%timeit
torch.matmul(tensor, tensor)

1.08 µs ± 5.16 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`


In [65]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 3))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x3)

In [67]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.1304, 0.5579],
        [0.6331, 1.4232]])

In [66]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.1599, 0.4392, 0.3430],
        [0.2033, 0.8234, 0.4604],
        [0.1510, 0.9055, 0.3687]])

In [68]:
torch.matmul(torch.rand(2, 2), torch.rand(2, 2))

tensor([[0.3550, 0.6589],
        [0.0884, 0.3492]])

### One  of the most common errors in deep learning: shape errors

In [70]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B) # Will not work, because the inner dimensions are not match

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [71]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [72]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [73]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [74]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [75]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [76]:
# Find the mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
# We can change the datatype

In [78]:
# torch.mean() function requires a tensor of float32 datatype to work
x.mean(dtype=torch.float32)

tensor(45.)

In [79]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [80]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [81]:
# Find the position in tensor that has the minimum value with argmin() -> return index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [82]:
x[0]

tensor(0)

In [85]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [86]:
x[9]

tensor(90)

## Reshaping , stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [87]:
import torch

In [88]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [91]:
# Add an extra dimension
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [92]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [94]:
x = torch.arange(1., 11.)
print(x)
x_reshaped = x.reshape(2, 5)
x_reshaped

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [95]:
# Change the view
x = torch.arange(1., 10.)
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [96]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [99]:
# Stack tensors on top of each other
x_stacked = torch.stack((x, x, x, x), dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [100]:
# Stack tensors on top of each other
x_stacked = torch.stack((x, x, x, x), dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [109]:
# torch.squeeze() - removes all single dimensions from a target tensor
x
x_reshaped = x.reshape((1,9))

print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [104]:
x_reshaped.shape

torch.Size([1, 9])

In [106]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [107]:
x_reshaped.squeeze().shape

torch.Size([9])

In [110]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [111]:
x_squeezed.unsqueeze(dim=1)

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [116]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
x_permuted.shape

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [117]:
x_original[0,0, :]

tensor([0.0233, 0.9552, 0.0066])

In [118]:
x_permuted[:, 0, 0]

tensor([0.0233, 0.9552, 0.0066])