## 00. PyTorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [2]:
import torch
import pandas as pd
import numpy as np
import plotly.express as px
print(torch.__version__)

2.0.1+cu118


In [3]:
!nvidia-smi

Wed Aug  9 20:04:47 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.67                 Driver Version: 536.67       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090      WDDM  | 00000000:01:00.0  On |                  Off |
|  0%   37C    P8              20W / 450W |    961MiB / 24564MiB |      8%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Introduction to Tensors

### Creating tensors

In [4]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

In [16]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are imrtant becau the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers -> ...`

In [20]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(1, 10, 10)
random_tensor

tensor([[[0.4570, 0.4166, 0.2337, 0.3485, 0.4416, 0.6975, 0.5694, 0.5115,
          0.6803, 0.3534],
         [0.0489, 0.2912, 0.3648, 0.3862, 0.2141, 0.3760, 0.9374, 0.2230,
          0.3231, 0.3142],
         [0.0090, 0.8559, 0.8331, 0.2194, 0.4221, 0.6825, 0.8643, 0.0085,
          0.4953, 0.9831],
         [0.0153, 0.2337, 0.5214, 0.8048, 0.8797, 0.0251, 0.8141, 0.8197,
          0.6943, 0.8928],
         [0.5367, 0.9495, 0.1563, 0.8114, 0.4002, 0.4694, 0.0972, 0.3191,
          0.5912, 0.4135],
         [0.3884, 0.5858, 0.5750, 0.4303, 0.7716, 0.5127, 0.8690, 0.4044,
          0.7273, 0.6532],
         [0.2312, 0.7379, 0.1766, 0.8066, 0.8194, 0.3791, 0.4541, 0.1268,
          0.3339, 0.1928],
         [0.0992, 0.2843, 0.2695, 0.4887, 0.7684, 0.5928, 0.2394, 0.7571,
          0.6592, 0.0030],
         [0.2058, 0.2531, 0.6980, 0.2081, 0.2590, 0.5266, 0.2336, 0.3856,
          0.9229, 0.3217],
         [0.3529, 0.8322, 0.4443, 0.1486, 0.7298, 0.1222, 0.4153, 0.6160,
          0.7522,

In [22]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)